name: MATLAB Workflow

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        matlab-version: R2022a

    - name: Run MATLAB script
      run: |
        matlab -batch "run('fb.m')"
